.PHONY: clean All

All:
	@echo "----------Building project:[ CityGraph - Debug ]----------"
	@cd "3-2" && "$(MAKE)" -f  "CityGraph.mk"
clean:
	@echo "----------Cleaning project:[ CityGraph - Debug ]----------"
	@cd "3-2" && "$(MAKE)" -f  "CityGraph.mk" clean
