.PHONY: clean All

All:
	@echo "----------Building project:[ FootballTeam - Debug ]----------"
	@cd "3-0" && "$(MAKE)" -f  "FootballTeam.mk"
clean:
	@echo "----------Cleaning project:[ FootballTeam - Debug ]----------"
	@cd "3-0" && "$(MAKE)" -f  "FootballTeam.mk" clean
