.PHONY: clean All

All:
	@echo "----------Building project:[ FixedSet - Debug ]----------"
	@cd "3-1" && "$(MAKE)" -f  "FixedSet.mk"
clean:
	@echo "----------Cleaning project:[ FixedSet - Debug ]----------"
	@cd "3-1" && "$(MAKE)" -f  "FixedSet.mk" clean
